package info

type RuleData struct {
	Name string
	Type string
	Rule string
}

type Md5Data struct {
	Name   string
	Md5Str string
}

type PocData struct {
	Name  string
	Alias string
}

var RuleDatas = []RuleData{
	{"Anquanbao", "headers", "(Anquanbao)"},
	{"BaiduYunjiasu", "headers", "(yunjiasu)"},
	{"BigIP", "headers", "(BigIP|BIGipServer)"},
	{"BinarySEC", "headers", "(binarysec)"},
	{"BlockDoS", "headers", "(BlockDos.net)"},
	{"CloudFlare", "headers", "(cloudflare)"},
	{"Cloudfront", "headers", "(cloudfront)"},
	{"Comodo", "headers", "(Protected by COMODO)"},
	{"IBM-DataPower", "headers", "(X-Backside-Transport)"},
	{"DenyAll", "headers", "(sessioncookie=)"},
	{"dotDefender", "headers", "(dotDefender)"},
	{"Incapsula", "headers", "(X-CDN|Incapsula)"},
	{"Jiasule", "headers", "(jsluid=)"},
	{"KONA", "headers", "(AkamaiGHost)"},
	{"ModSecurity", "headers", "(Mod_Security|NOYB)"},
	{"NetContinuum", "headers", "(Cneonction|nnCoection|citrix_ns_id)"},
	{"Newdefend", "headers", "(newdefend)"},
	{"Safe3", "headers", "(Safe3WAF|Safe3 Web Firewall)"},
	{"Safedog", "code", "(404.safedog.cn/images/safedogsite/broswer_logo.jpg)"},
	{"Safedog", "headers", "(Safedog|WAF/2.0)"},
	{"SonicWALL", "headers", "(SonicWALL)"},
	{"Stingray", "headers", "(X-Mapping-)"},
	{"Sucuri", "headers", "(Sucuri/Cloudproxy)"},
	{"Usp-Sec", "headers", "(Secure Entry Server)"},
	{"Varnish", "headers", "(varnish)"},
	{"Wallarm", "headers", "(wallarm)"},
	{"Alibaba Cloud", "code", "(errors.aliyun.com)"},
	{"WebKnight", "headers", "(WebKnight)"},
	{"Yundun", "headers", "(YUNDUN)"},
	{"Yunsuo", "headers", "(yunsuo)"},
	{"Coding pages", "header", "(Coding Pages)"},
	{"Qiming Firewall", "body", "(/cgi-bin/webui?op=get_product_model)"},
	{"Shiro", "headers", "(=deleteMe|rememberMe=)"},
	{"Portainer (Docker management)", "code", "(portainer.updatePassword|portainer.init.admin)"},
	{"Gogs (Simple Git service)", "cookie", "(i_like_gogs)"},
	{"Gitea (Simple Git service)", "cookie", "(i_like_gitea)"},
	{"Nexus", "code", "(Nexus Repository Manager)"},
	{"Nexus", "cookie", "(NX-ANTI-CSRF-TOKEN)"},
	{"Harbor", "code", "(<title>Harbor</title>)"},
	{"Harbor", "cookie", "(harbor-lang)"},
	{"Zentao", "code", "(/theme/default/images/main/zt-logo.png|/zentao/theme/zui/css/min.css)"},
	{"Zentao", "cookie", "(zentaosid)"},
	{"Xiezhong OA", "code", "(Powered by Xiezhong OA)"},
	{"Xiezhong OA", "cookie", "(CNOAOASESSID)"},
	{"xxl-job", "code", "(Distributed task scheduling platform XXL-JOB)"},
	{"atmail-WebMail", "cookie", "(atmail6)"},
	{"atmail-WebMail", "code", "(/index.php/mail/auth/processlogin|Powered by Atmail)"},
	{"weblogic", "code", "(/console/framework/skins/wlsconsole/images/login_WebLogic_branding.png|Welcome to Weblogic Application Server|<i>Hypertext Transfer Protocol -- HTTP/1.1</i>)"},
	{"Zhiyuan OA", "code", "(/seeyon/common/|/seeyon/USER-DATA/IMAGES/LOGIN/login.gif)"},
	{"discuz", "code", "(content=\"Discuz! X\")"},
	{"Typecho", "code", "(Typecho</a>)"},
	{"Kingdee EAS", "code", "(easSessionId)"},
	{"phpMyAdmin", "cookie", "(pma_lang|phpMyAdmin)"},
	{"phpMyAdmin", "code", "(/themes/pmahomme/img/logo_right.png)"},
	{"H3C-AM8000", "code", "(AM8000)"},
	{"360 Enterprise Edition", "code", "(360EntWebAdminMD5Secret)"},
	{"H3C Company Products", "code", "(service@h3c.com)"},
	{"H3C ICG 1000", "code", "(ICG 1000System)"},
	{"Citrix-Metaframe", "code", "(window.location=\"/Citrix/MetaFrame)"},
	{"H3C ER5100", "code", "(ER5100System)"},
	{"阿里云CDN", "code", "(cdn.aliyuncs.com)"},
	{"CISCO_EPC3925", "code", "(Docsis_system)"},
	{"CISCO ASR", "code", "(CISCO ASR)"},
	{"H3C ER3200", "code", "(ER3200System)"},
	{"万户oa", "code", "(/defaultroot/templates/template_system/common/css/|/defaultroot/scripts/|css/css_whir.css)"},
	{"Spark_Master", "code", "(Spark Master at)"},
	{"HUAWEI_SRG2220", "code", "(HUAWEI SRG2220)"},
	{"Lan Ling OA", "code", "(/scripts/jquery.landray.common.js)"},
	{"Sangfor ssl-vpn", "code", "(login_psw.csp)"},
	{"Huawei NetOpen", "code", "(/netopen/theme/css/inFrame.css)"},
	{"Citrix-Web-PN-Server", "code", "(Citrix Web PN Server)"},
	{"juniper_vpn", "code", "(welcome.cgi?p=logo|/images/logo_juniper_reversed.gif)"},
	{"360 Host Guardian", "headers", "(zhuji.360.cn)"},
	{"Nagios", "headers", "(Nagios Access)"},
	{"H3C ER8300", "code", "(ER8300System)"},
	{"Citrix-Access-Gateway", "code", "(Citrix Access Gateway)"},
	{"MCU", "code", "(McuR5-min.js)"},
	{"TP-LINK Wireless WDR3600", "code", "(TP-LINK Wireless WDR3600)"},
	{"FusionOffice OA", "headers", "(ecology_JSessionid)"},
	{"FusionOffice OA", "code", "(/spa/portal/public/index.js)"},
	{"HUAWEI_ASG2050", "code", "(HUAWEI ASG2050)"},
	{"360 Website Guardian", "code", "(360wzb)"},
	{"Citrix-XenServer", "code", "(Citrix Systems, Inc. XenServer)"},
	{"H3C ER2100V2", "code", "(ER2100V2System)"},
	{"zabbix", "cookie", "(zbx_sessionid)"},
	{"zabbix", "code", "(images/general/zabbix.ico|Zabbix SIA|zabbix-server: Zabbix)"},
	{"CISCO_VPN", "headers", "(webvpn)"},
	{"360站长平台", "code", "(360-site-verification)"},
	{"H3C ER3108GW", "code", "(ER3108GWSystem)"},
	{"o2security_vpn", "headers", "(client_param=install_active)"},
	{"H3C ER3260G2", "code", "(ER3260G2System)"},
	{"H3C ICG1000", "code", "(ICG1000System)"},
	{"CISCO-CX20", "code", "(CISCO-CX20)"},
	{"H3C ER5200", "code", "(ER5200System)"},
	{"linksys-vpn-bragap14-parintins", "code", "(linksys-vpn-bragap14-parintins)"},
	{"360 website guardian", "code", "(libs.useso.com)"},
	{"H3C ER3100", "code", "(ER3100System)"},
	{"H3C-SecBlade-FireWall", "code", "(js/MulPlatAPI.js)"},
	{"360webfacil_360WebManager", "code", "(publico/template/)"},
	{"Citrix_Netscaler", "code", "(ns_af)"},
	{"H3C ER6300G2", "code", "(ER6300G2System)"},
	{"H3C ER3260", "code", "(ER3260System)"},
	{"HUAWEI_SRG3250", "code", "(HUAWEI SRG3250)"},
	{"exchange", "code", "(/owa/auth.owa|Exchange Admin Center)"},
	{"Spark_Worker", "code", "(Spark Worker at)"},
	{"H3C ER3108G", "code", "(ER3108GSystem)"},
	{"Citrix-ConfProxy", "code", "(confproxy)"},
	{"360 website security scan", "code", "(webscan.360.cn/status/pai/hash)"},
	{"H3C ER5200G2", "code", "(ER5200G2System)"},
	{"HUAWEI Security", "code", "(sweb-lib/resource/)"},
	{"HUAWEI USG", "code", "(UI_component/commonDefine/UI_regex_define.js)"},
	{"H3C ER6300", "code", "(ER6300System)"},
	{"HUAWEI_ASG2100", "code", "(HUAWEI ASG2100)"},
	{"TP-Link 3600 DD-WRT", "code", "(TP-Link 3600 DD-WRT)"},
	{"NETGEAR WNDR3600", "code", "(NETGEAR WNDR3600)"},
	{"H3C ER2100", "code", "(ER2100System)"},
	{"jira", "code", "(jira.webresources)"},
	{"Jinhe Collaborative Management Platform", "code", "(Jinhe Collaborative Management Platform)"},
	{"Citrix-NetScaler", "code", "(NS-CACHE)"},
	{"linksys-vpn", "headers", "(linksys-vpn)"},
	{"Tongda OA", "code", "(/static/images/tongda.ico|http://www.tongda2000.com|Tongda OA Mobile Edition|Office Anywhere)"},
	{"HUAWEI Secoway", "code", "(Secoway)"},
	{"HUAWEI_SRG1220", "code", "(HUAWEI SRG1220)"},
	{"H3C ER2100n", "code", "(ER2100nSystem)"},
	{"H3C ER8300G2", "code", "(ER8300G2System)"},
	{"Kingdee Government Solutions GSiS", "code", "(/kdgs/script/kdgs.js)"},
	{"Jboss", "code", "(Welcome to JBoss|jboss.css)"},
	{"Jboss", "headers", "(JBoss)"},
	{"FANWEI E-mobile", "code", "(Weaver E-mobile|weaver,e-mobile)"},
	{"FANWEI E-mobile", "headers", "(EMobileServer)"},
	{"Qizhi Bastion Machine", "code", "(logo-icon-ico72.png|resources/themes/images/logo-login.png)"},
	{"ThinkPHP", "headers", "(ThinkPHP)"},
	{"ThinkPHP", "code", "(/Public/static/js/)"},
	{"weaver-ebridge", "code", "(e-Bridge,http://wx.weaver)"},
	{"Laravel", "headers", "(laravel_session)"},
	{"DWR", "code", "(dwr/engine.js)"},
	{"swagger_ui", "code", "(swagger-ui/css|\"swagger\":|swagger-ui.min.js)"},
	{"Da Han Edition Tong Publishing System", "code", "(Da Han Edition Tong Publishing System|Da Han Network)"},
	{"druid", "code", "(druid.index|DruidDrivers|DruidVersion|Druid Stat Index)"},
	{"Jenkins", "code", "(Jenkins)"},
	{"Red Sail OA", "code", "(iOffice)"},
	{"VMware vSphere", "code", "(VMware vSphere)"},
	{"Printer", "code", "(Printer|media/canon.gif)"},
	{"finereport", "code", "(isSupportForgetPwd|FineReport,Web Reporting Tool)"},
	{"Lan Ling OA", "code", "(Lan Ling Software|StylePath:\"/resource/style/default/\"|/resource/customization|sys/ui/extend/theme/default/style/profile.css|sys/ui/extend/theme/default/style/icon.css)"},
	{"GitLab", "code", "(href=\"https://about.gitlab.com/)"},
	{"Jquery-1.7.2", "code", "(/webui/js/jquerylib/jquery-1.7.2.min.js)"},
	{"Hadoop Applications", "code", "(/cluster/app/application)"},
	{"Sangfor Firewall products", "code", "(SANGFOR FW)"},
	{"360 Website Defender", "code", "(webscan.360.cn/status/pai/hash|wzws-waf-cgi|zhuji.360.cn/guard/firewall/stopattack.html)"},
	{"360 Website Defender", "headers", "(360wzws|CWAP-waf|zhuji.360.cn|X-Safe-Firewall)"},
	{"Green Alliance Firewall", "code", "(NSFOCUS NF)"},
	{"Green Alliance Firewall", "headers", "(NSFocus)"},
	{"Topsec-Waf", "index", `(<META NAME="Copyright" CONTENT="Topsec Network Security Technology Co.,Ltd"/>","<META NAME="DESCRIPTION" CONTENT="Topsec web UI"/>)`},
    {"Baota", "body", "(app.bt.cn/static/app.png|Security entry verification failed|<title>Entry verification failed</title>|href=\"http://www.bt.cn/bbs)"},
    {"Haichang OA", "code", "(/loginmain4/js/jquery.min.js)"},
    {"FineReport", "code", "(WebReport/login.html|ReportServer)"},
    {"FineReport", "headers", "(Data Decision System)"},
    {"Huaxia ERP", "headers", "(Huaxia ERP)"},
    {"Jinhe OA", "cookie", "(ASPSESSIONIDSSCDTDBS)"},
    {"Jiuqi Financial Report", "code", "(netrep/login.jsp|/netrep/intf)"},
    {"RuoYi Management System", "code", "(ruoyi/login.js|ruoyi/js/ry-ui.js)"},
    {"Qilai OA", "code", "(js/jQselect.js|js/jquery-1.4.2.min.js)"},
    {"Smart Campus Management System", "code","(DC_Login/QYSignUp)"},
    {"JQuery-1.7.2","code","(webui/js/jquerylib/jquery-1.7.2.min.js)"},
    {"Inspur ClusterEngineV4.0","code","(0;url=module/login/login.html)"},
    {"Huijietong Cloud Video Platform","code","(him/api/rest/v1.0/node/role|him.app)"},
    {"Source code leakage username and password F12 view","code","(get_dkey_passwd)"},
    {"Smartbi Insight","code","(smartbi.gcf.gcfutil)"},
    {"Hanwang Facial Attendance Management System ","code","(Hanwang Facial Attendance Management System |/Content/image/hanvan.png|/Content/image/hvicon.ico)"},
    {"Yisaotong - Electronic Document Security Management System "," code "," (Electronic Document Security Management System |/ CDGServer3/index.jsp |/ CDGServer3/SysConfig.jsp |/ CDGServer3/help/getEditionInfo.jsp) "},
    {"Tianrongxin TopApp-LB Load Balancing System ","code","(TopApp-LB Load Balancing System)"},
    {"Zhongxin Jindun Information Security Management System ","code","(Zhongxin Jindun Information Security Management System | Zhongxin Network Information Security Co., Ltd.)"},
    {"Haoshitong","code","(Shenzhen Yinpeng Cloud Computing Co., Ltd. | itunes.apple.com/us/app/id549407870|hao-shi-tong-yun-hui-yi-yuan)"},
    {"Blue Ocean Excellent Billing Management System","code","(Blue Ocean Excellent Billing Management System | Xingrui Blue Ocean Network Technology Co., Ltd.)"},
    {"Hexin Chuangtian Cloud Desktop System ","code","(Hexin Next Generation Cloud Desktop VENGD |/vesystem/index.php)"},
    {"Jinshan", "code", "(Beijing Eagle Security Technology Co., Ltd. | Jinshan Terminal Security System V9.0 Web Console | Beijing Jinshan Security Management System Technology Co., Ltd. | Jinshan V8)"},
    {"WIFISKY-7 Layer Flow Control Router", "code", "(Shenzhen Lingkong Technology Co., Ltd. | WIFISKY 7 Layer Flow Control Router)"},
    {"MetInfo - Metinfo Station Building", "code", "(MetInfo|/skin/style/metinfo.css|/skin/style/metinfo-v2.css)"},
    {"IBM Lotus Domino", "code", "(/mailjump.nsf|/domcfg.nsf|/names.nsf|/homepage.nsf)"},
    {"APACHE-kylin", "code", "(url=kylin)"},
    {"C-Lodop Printing Service System ", "code ", "(/CLodopfuncs.js|www.c-lodop.com)"},
    {"HFS", "code", "(href=\"http://www.rejetto.com/hfs/)"},
    {"Jellyfin", "code", "(content=\"http://jellyfin.org\")"},
    {"FIT2CLOUD-JumpServer Bastion Host ", "code", "(<title>JumpServer</title>)"},
    {"Alibaba Nacos", "code", "(<title>Nacos</title>)"},
    {"Nagios","headers","(nagios admin)"},
    {"Pulse Connect Secure","code","(/dana-na/imgs/space.gif)"},
    {"h5ai","code","(powered by h5ai)"},
    {"jeesite","cookie","(jeesite.session.id)"},
    {"Torres SSO","cookie","(trsidsssosessionid)"},
    {"Torres WCMv7/6 ","cookie "," (com.trs.idm.coSessionId) "},
    {"Tianrongxin Vulnerability Scanning and Management System "," code "," (/js/report/horizontalReportPanel.js) "},
    {"Tianrongxin Network Audit System ", "code", "(onclick=dlg_download())"},
    {"Tianrongxin Log Collection and Analysis System ", "code", "(Tianrongxin Log Collection and Analysis System)"},
    {"URP Education Management System ", "code", "(Beijing Qingyuan Excellent Software Technology Co., Ltd.)"},
    {"Kolay RAS ", "code", "(Kolay Software All rights reserved | i18ninit.min.js)"},
    {"Zhengfang OA ", "code", "(zfoausername)"},
    {"Heer OA "," code "," (/heeroa/login.do) "},
    {"Fangpu Construction Engineering Construction OA "," code "," (/dwr/interface/LoginService.js) "},
    {"Zhongwang OA "," code "," (/IMAGES/default/first/xtoa_logo.png |/app_qjuserinfo/qjuserinfoadd.jsp) "},
    {"Haitian OA "," code "," (HTVOS.js) "},
    {"Xinda OA ", "code", "(http://www.xdoa.cn</a>)"},
    {"Renwoxing CRM", "code", "(CRM_LASTLOGINUSERKEY)"},
    {"Spammark Email Information Security Gateway","code","(/cgi-bin/spammark?empty=1)"},
    {"winwebmail", "code", "(WinWebMail Server|images/owin.css)"},
    {"LangChao Government Affairs System", "code", "(LangChao.ECGAP.OutPortal|OnlineQuery/QueryList.aspx)"},
    {"Topsec Firewall", "code", "(/cgi/maincgi.cgi)"},
    {"NetentSec Firewall", "code", "(css/lsec/login.css)"},
    {"Paladin Unified Security Management and Comprehensive Audit System", "code", "(module/image/pldsec.css)"},
    {"Blue Shield BDWebGuard", "code", "(BACKGROUND: url(images/loginbg.jpg) #e5f1fc)"},
    {"Huawei SMC", "code", "(Script/SmcScript.js?version=)"},
    {"Coremail", "code", "(/coremail/bundle/|contextRoot: \"/coremail\"|coremail/common)"},
    {"ActiveMQ", "code", "(activemq_logo|Manage ActiveMQ broker)"},
    {"Ruijie Networks", "code", "(static/img/title.ico|support.ruijie.com.cn|Ruijie - NBR|eg.login.loginBtn)"},
    {"Zentao Project Management Software ", "code","(/theme/default/images/main/zt-logo.png|zentaosid)"},
    {"Weblogic","code","(/console/framework/skins/wlsconsole/images/login_WebLogic_branding.png|Welcome to Weblogic Application Server|<i>Hypertext Transfer Protocol -- HTTP/1.1</i>|<TITLE>Error 404--Not Found</TITLE>|Welcome to Weblogic Application Server|<title>Oracle WebLogic Server Administration Console</title>)"},
    {"Weblogic","headers","(WebLogic)"},
    {"Seeyon OA","code","(/seeyon/USER-DATA/IMAGES/LOGIN/login.gif|/seeyon/common/)"},
    {"Landray EIS Intelligent Collaboration Platform","code","(/scripts/jquery.landray.common.js)"},
    {"Sangfor SSL-VPN","code","(login_psw.csp|loginPageSP/loginPrivacy.js|/por/login_psw.csp)"},
    {"Struts2","code","(org.apache.struts2|Struts Problem Report|struts.devMode|struts-tags|There is no Action mapped for namespace)"},
    {"Fusion OA","code","(/spa/portal/public/index.js|wui/theme/ecology8/page/images/login/username_wev8.png|/wui/index.html#/?logintype=1)"},
    {"Swagger UI","code","(/swagger-ui.css|swagger-ui-bundle.js|swagger-ui-standalone-preset.js)"},
    {"Kingdee Government Service GSiS","code","(/kdgs/script/kdgs.js|HTML5/content/themes/kdcss.min.css|/ClientBin/Kingdee.BOS.XPF.App.xap)"},
    {"Lanling OA", "code", "(Lanling Software|StylePath:\"/resource/style/default/\"|/resource/customization|sys/ui/extend/theme/default/style/icon.css|sys/ui/extend/theme/default/style/profile.css)"},
    {"Yonyou NC", "code", "(Yonyou UAP|YONYOU NC|/Client/Uclient/UClient.dmg|logo/images/ufida_nc.png|iUFO/web/css/menu.css|.nc/servlet/iufo.login.Index)"},
    {"Yonyou iUFO", "code", "(iUFO/web/css/menu.css)"},
    {"TELEPORT Bastion Host", "code", "(/static/plugins/blur/background-blur.js)"},
    {"JEECMS", "code", "(/r/cms/www/red/js/common.js|r/cms/www/red/js/indexshow.js)|Powered by JEECMS |JEECMS |jadmin/jcms/index.do)"},
    {"CMS", "code", "(Powered by .*CMS)"},
    {"Directory Traversal", "code", "(Directory listing for /)"},
    {"ATLASSIAN-Confluence", "code", "(com.atlassian.confluence)"},
    {"ATLASSIAN-Confluence", "headers", "(X-Confluence)"},
    {"Sunflower Remote Control System", "code", "({\"success\":false,\"msg\":\"Verification failure\"})"},
    {"Kubernetes","code","(Kubernetes Dashboard</title>|Kubernetes Enterprise Manager|Mirantis Kubernetes Engine|Kubernetes Resource Report)"},
    {"WordPress","code","(/wp-login.php?action=lostpassword|WordPress</title>)"},
    {"RabbitMQ","code","(RabbitMQ Management)"},
    {"Dubbo","headers","(Basic realm=\"dubbo\")"},
    {"Spring Environment","code","(logback)"},
    {"Ueditor","code","(ueditor.all.js|UE.getEditor)"},
    {"Yiyou Email System ","code","(Yiyou Email System|Yiyou Email Overall Solution)"},
}

var Md5Datas = []Md5Data{
    {"BIG-IP", "04d9541338e525258daf47cc844d59f3"},
    {"Landray OA", "302464c3f6207d57240649926cfc7bd4"},
    {"JBOSS", "799f70b71314a7508326d1d2f68f7519"},
    {"Ruijie Networks", "d8d7c9138e93d43579ebf2e384745ba8"},
    {"Ruijie Networks", "9c21df9129aeec032df8ac15c84e050d"},
    {"Ruijie Networks", "a45883b12d753bc87aff5bddbef16ab3"},
    {"Sangfor EDR", "0b24d4d5c7d300d50ee1cd96059a9e85"},
    {"ZhongYuan OA", "cdc85452665e7708caed3009ecb7d4e2"},
    {"ZhongYuan OA", "17ac348fcce0b320e7bfab3fe2858dfa"},
    {"ZhongYuan OA", "57f307ad3764553df84e7b14b7a85432"},
    {"ZhongYuan OA", "3c8df395ec2cbd72782286d18a286a9a"},
    {"ZhongYuan OA", "2f761c27b6b7f9386bbd61403635dc42"},
    {"Qizhi Bastion Machine", "48ee373f098d8e96e53b7dd778f09ff4"},
    {"SpringBoot", "0488faca4c19046b94d07c3ee83cf9d6"},
    {"ThinkPHP", "f49c4a4bde1eec6c0b80c2277c76e3db"},
    {"Tongda OA", "ed0044587917c76d08573577c8b72883"},
    {"FusionInsight E-mobile", "41eca7a9245394106a09b2534d8030df"},
    {"FusionInsight OA", "c27547e27e1d2c7514545cd8d5988946"},
    {"FusionInsight OA", "9b1d3f08ede38dbe699d6b2e72a8febb"},
    {"FusionInsight OA", "281348dd57383c1f214ffb8aed3a1210"},
    {"GitLab", "85c754581e1d4b628be5b7712c042224"},
    {"Hikvision Surveillance", "89b932fcc47cf4ca3faadb0cfdef89cf"},
    {"Huaxia ERP", "c68b15c45cf80115a943772f7d0028a6"},
    {"OpenSNS", "08711abfb016a55c0e84f7b54bef5632"},
    {"MetInfo - Mituo Website Construction", "2a9541b5c2225ed2f28734c0d75e456f"},
    {"IBM Lotus Domino", "36c1002bb579edf52a472b9d2e39bb50"},
    {"IBM Lotus Domino", "639b61409215d770a99667b446c80ea1"},
    {"ATLASSIAN Confluence", "b91d19259cf480661ef93b67beb45234"},
    {"ActiveMQ", "05664fb0c7afcd6436179437e31f3aa6"},
    {"Coremail", "ad74ff8f9a2f630fc2c5e6b3aa0a5cb8"},
}

var PocDatas = []PocData{
    {"ZhongYuan OA", "seeyon"},
    {"FusionInsight OA", "weaver"},
    {"Tongda OA", "tongda"},
    {"Landray OA", "landray"},
    {"ThinkPHP", "thinkphp"},
    {"Nexus", "nexus"},
    {"Qizhi Bastion Machine", "qizhi"},
    {"Weaver E-Bridge", "weaver-ebridge"},
    {"WebLogic", "weblogic"},
    {"Zabbix", "zabbix"},
    {"VMware vSphere", "vmware"},
    {"Jboss", "jboss"},
    {"Yonyou", "yongyou"},
    {"Yonyou IUFO", "yongyou"},
    {"Coremail", "coremail"},
    {"Kingsoft", "kingsoft"},
}
